runtime: go125

# this is annoying.
handlers:
  # "meta" files for a site
 - url: /sitemap.xml
   static_files: static/sitemap.xml
   upload: static/sitemap.xml
   secure: optional
 - url: /robots.txt
   static_files: static/robots.txt
   upload: static/robots.txt
   secure: optional
 - url: /icon.svg
   static_files: static/icon.svg
   upload: static/icon.svg
   secure: optional

  # top level html
 - url: /
   static_files: static/index.html
   upload: static/index.html
   secure: optional
 - url: /guidelines.html
   static_files: static/guidelines.html
   upload: static/guidelines.html
   secure: optional

  # /es
 - url: /es
   static_files: static/es/index.html
   upload: static/es/index.html
   secure: optional
 - url: /es/
   static_files: static/es/index.html
   upload: static/es/index.html
   secure: optional
 - url: /es/index.html
   static_files: static/es/index.html
   upload: static/es/index.html
   secure: optional
 - url: /es/paper.html
   static_files: static/es/paper.html
   upload: static/es/paper.html
   secure: optional
 - url: /es/man.txt
   static_files: static/es/man.txt
   upload: static/es/man.txt
   secure: optional

  # /toki
 - url: /toki
   static_files: static/toki/index.html
   upload: static/toki/index.html
   secure: optional
 - url: /toki/
   static_files: static/toki/index.html
   upload: static/toki/index.html
   secure: optional
 - url: /toki/index.html
   static_files: static/toki/index.html
   upload: static/toki/index.html
   secure: optional
 - url: /toki/linluwi.html
   static_files: static/toki/linluwi.html
   upload: static/toki/linluwi.html
   secure: optional

  # /style -- can do an actual static dir, since no html
 - url: /style/
   static_dir: static/style
   secure: optional
