name: 'Dump into Cloud Run'

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: 'jpco-cloud'
  REGION: 'us-west1'
  SERVICE: 'web'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/575814038185/locations/global/workloadIdentityPools/github/providers/jws-site'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{env.WORKLOAD_IDENTITY_PROVIDER}}'
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'

      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
