# The default service handles serving the static site, blog, and other 'utility' functions.

runtime: go112

handlers:
# redirect to go.jpco.io, and since that one is potentially secure: optional,
# be secure: optional here
 - url: /go.*
   script: auto
   secure: optional

# static site handlers
 - url:  /
   static_files: public/index.html
   upload: /
   secure: always
 - url: /css
   static_dir: public/css
   secure: always
   mime_type: text/css
 - url: /fonts
   static_dir: public/fonts
   secure: always
 - url: /js
   static_dir: public/js
   mime_type: text/javascript
   secure: always
 - url: /media
   static_dir: public/media
   secure: always
 - url: /(.*).txt
   static_files: public/\1.txt
   upload: .*\.txt
   secure: optional
 - url: /dogs.json
   static_files: public/dogs.json
   upload: public/dogs.json
   secure: optional
 - url: /sitemap.xml
   static_files: public/sitemap.xml
   upload: public/sitemap.xml
   secure: optional
 - url: /(.*).html$
   static_files: public/\1.html
   upload: .*\.html
   secure: always
 - url: /(.*)/$
   static_files: public/\1/index.html
   upload: .*\.html
   secure: always
 - url: /(.*)
   static_files: public/\1/index.html
   upload: .*\.html
   secure: always
