baseURL = "/"
languageCode = "en-us"
title = "jpco dot io"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodefences = true
pygmentsStyle = "lovelace"

[outputs]
 home = ["HTML"]
 page = ["HTML"]

[markup.goldmark.renderer]
unsafe = true
