baseURL = "/"
languageCode = "en-us"
title = "jpco web services"
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodefences = true
pygmentsStyle = "lovelace"

[outputs]
 home = ["HTML"]
 page = ["HTML"]
